name: Environtment Variables
on: workflow_dispatch
jobs:
  test:
    env:
      MY_ENV: ${{ secrets.APP_NAME }}

    runs-on: ubuntu-latest
    steps:
      - name: Get codes
        uses: actions/checkout@v3

      - name: Install Deps
        run: npm ci

      - name: Test Codes
        run: npm run test

      - name: Echo Env
        run: |
          echo "$MY_ENV"
          echo "MY_ENV: ${{ env.MY_ENV }}"
