name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check yarn version
        run: yarn --version
      - name: Get the codes
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install Deps
        run: yarn install --frozen-lockfile
      - name: Run Test
        run: yarn test
